"""
Lifecycle Cog
Monitors Polymarket promotion gate reports and streams autonomy events to Discord.
"""

import os
import json
import asyncio
from datetime import datetime
from typing import Any, Dict, Optional

import discord
from discord.ext import commands, tasks

from src.utils.logger import get_logger
from src.bot.runtime_routing import resolve_channel

logger = get_logger(__name__)

class LifecycleCog(commands.Cog):
    """
    Cog for monitoring the Polymarket autonomy lifecycle.
    Polls the promotion gate report file and alerts on state changes.
    """

    def __init__(self, bot: commands.Bot):
        self.bot = bot
        # Path to the report generated by scripts/polymarket/run_polymarket_promotion_gate.py
        self.report_path = "scripts/polymarket/polymarket_promotion_gate_report.json"
        self.last_verdict: Optional[str] = None
        self.last_tier: Optional[str] = None
        self.last_reason: Optional[str] = None

        # Start the monitoring loop
        self.monitor_lifecycle.start()

    def cog_unload(self):
        self.monitor_lifecycle.stop()

    @tasks.loop(minutes=10)
    async def monitor_lifecycle(self):
        """Poll the promotion report for changes in bot autonomy state."""
        try:
            if not os.path.exists(self.report_path):
                logger.debug(f"Lifecycle report not found at {self.report_path}, skipping...")
                return

            with open(self.report_path, "r") as f:
                data = json.load(f)

            verdict = data.get("verdict")
            target_tier = data.get("target_tier")
            primary_reason = data.get("primary_reason", "No specific reason")

            if verdict is None or target_tier is None:
                return

            # Detect state changes
            if verdict != self.last_verdict or target_tier != self.last_tier or primary_reason != self.last_reason:
                await self._handle_lifecycle_event(verdict, target_tier, primary_reason, data)

                self.last_verdict = verdict
                self.last_tier = target_tier
                self.last_reason = primary_reason

        except Exception as e:
            logger.error(f"Error monitoring lifecycle report: {e}", exc_info=True)

    async def _handle_lifecycle_event(self, verdict: str, tier: str, reason: str, full_data: Dict[str, Any]):
        """Process and notify the lifecycle event to Discord."""
        channel = resolve_channel(self.bot, "lifecycle") # Assumes 'lifecycle' key in discord_channel_contract.json
        if not channel:
            # Fallback to a general audit channel if lifecycle is not defined
            channel = resolve_channel(self.bot, "audit-token")

        if not channel:
            logger.warning("Could not resolve lifecycle or audit channel for notifications.")
            return

        # Build structured message
        if verdict == "PASS":
            emoji = "🚀"
            status = "PROMOTION APPROVED"
            content = (
                f"{emoji} **AUTONOMY PROMOTION**\n"
                f"The bot has passed the gates for **{tier}**.\n"
                f"**Reason**: {reason}\n"
                f"*Ready for transition to next tier.*"
            )
        elif verdict == "BLOCKED" and self.last_verdict == "PASS":
            emoji = "⚠️"
            status = "DEMOTION / RISK ALERT"
            content = (
                f"{emoji} **AUTONOMY DEMOTION**\n"
                f"Bot is now **BLOCKED** from promoting to **{tier}**.\n"
                f"**Critical Blocker**: {reason}\n"
                f"*Immediate attention required to restore sovereign stability.*"
            )
        elif verdict == "BLOCKED":
            emoji = "🛡️"
            status = "SOVEREIGN GUARD"
            content = (
                f"{emoji} **LIFECYCLE UPDATE**\n"
                f"Target Tier: **{tier}**\n"
                f"Status: **BLOCKED**\n"
                f"Current Blocker: `{reason}`"
            )
        else:
            content = f"🌐 **AUTONOMY UPDATE**: {tier} - {verdict} ({reason})"

        # Append KPI data if available (e.g. for R6 validation)
        kpis = full_data.get("kpi_summary")
        if kpis:
            kpi_text = "\n\n**Sovereign KPIs**:\n" + "\n".join([f"• {k}: {v}" for k, v in kpis.items()])
            content += kpi_text

        try:
            await channel.send(content)
            logger.info(f"Sent lifecycle update to Discord: {status} ({tier})")
        except Exception as e:
            logger.error(f"Failed to send lifecycle event to Discord: {e}")

async def setup(bot: commands.Bot):
    await bot.add_cog(LifecycleCog(bot))
